### ISSUE TITLE
aggiustamenti

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#1]
hai il file scuola.hpp e poi includi scuola.h

manca this->alunno = NULL nel secondo costruttore

quando fai l'allocazione dinamica devi usare len+1 (lo spazio per il terminatore)

**Comment by Billie99** [comment]
Grazie prof.. funziona tutto perfettamente!

**Comment by Billie99** [comment]
Prof.. ho modificato il programma! vedete se e' corretto!
