### ISSUE TITLE
Binario

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#13]
Hai mal interpretato l'esercizio

**Comment by Billie99** [comment]
Si lo so.. ma pensavo funzionasse

**Comment by FabioZTessitore** [comment]
Va meglio ma bisogna aggiustare ancora qualcosa. Un numero che termina con 0 oppure 1 è considerato binario. Es 321

**Comment by Billie99** [comment]
Prof ma come è possibile, ho provato con tutti i numeri possibili..

**Comment by FabioZTessitore** [comment]
Ti trovi con quello che ho scritto?

Il 8 giu 2017 7:16 AM, "Billie99" <notifications@github.com> ha scritto:

**Comment by Billie99** [comment]
Ho provato con il numero 321 mi dice che non e' binario, ma provando con il numero 112 dice che e' binario... come mai ?

**Comment by FabioZTessitore** [comment]
Si giusto. Lui legge i numeri a partire dall'ultima cifra. Quindi se la
prima è 1 dice che è binario.

Trovato il problema non resta che trovare una soluzione

Il 8 giu 2017 9:05 AM, "Billie99" <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Prova a non usare pow()

**Comment by Billie99** [comment]
Come senza pow ? C'e' un'altra strada?

**Comment by FabioZTessitore** [comment]
Certo. Suggerimento: non è necessario calcolare 2^i ogni volta

Il 8 giu 2017 10:01 PM, "Billie99" <notifications@github.com> ha scritto:
