### ISSUE TITLE
Cripta

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#14]
Manca qualcosa nella trasformazione

**Comment by Billie99** [comment]
Cosa ? Ho estratto la cifra sommandola a 7

**Comment by FabioZTessitore** [comment]
Non basta

**Comment by Billie99** [comment]
Prof da quello che ho capito, dopo estratto il numero e sommandolo a 7 devo farlo di nuovo in modulo 10 ?

**Comment by FabioZTessitore** [comment]
Si

Il 9 giu 2017 3:25 PM, "Billie99" <notifications@github.com> ha scritto:

Prof da quello che ho capito, dopo estratto il numero e sommandolo a 7 devo
farlo di nuovo in modulo 10 ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Billie99/C/issues/14#issuecomment-307387812>, or mute
the thread

**Comment by FabioZTessitore** [comment]
bisogna aggiustare decripta. la funzione di decifratura che hai trovato non è corretta (prova a fare dei test)

**Comment by Billie99** [comment]
Si lo so.. cripta va bene?

**Comment by FabioZTessitore** [comment]
Si

Il 10 giu 2017 1:19 PM, "Billie99" <notifications@github.com> ha scritto:

Si lo so.. cripta va bene?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Billie99/C/issues/14#issuecomment-307559113>, or mute
the thread
