### ISSUE TITLE
somma cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#4]
in attesa

**Comment by Billie99** [comment]
Fatto prof..

**Comment by FabioZTessitore** [comment]
Visto che hai messo return 0 nell'if non c'è bisogno dell'else.

Ps perché hai tolto const dall'altro esercizio?

**Comment by Billie99** [comment]
Prof il fatto della constante globale! In classe avevate detto di correggere!

**Comment by FabioZTessitore** [comment]
Avevo detto che andava bene proprio perché è una costante

Il 3 feb 2017 10:28 PM, "Billie99" <notifications@github.com> ha scritto:

**Comment by Billie99** [comment]
Ahh.. Allora ho capito male scusate! Comunque mi sono esercitato su Python sulle funzioni e classi!
vi sono arrivate le notifiche?

**Comment by FabioZTessitore** [comment]
Si si. Tutto ok, bravo
