### ISSUE TITLE
sumvett

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#5]
togli quel system("pause")

**Comment by Billie99** [comment]
Perche prof non serve?

**Comment by FabioZTessitore** [comment]
Perché noi usiamo linux, quello lo hai fatto con devc su win

**Comment by Billie99** [comment]
Ah ho capito!

**Comment by Billie99** [comment]
Prof guardate questo programma! E' un po particolare riguarda la
programmazione ad oggetti..
​

2017-03-10 7:10 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by Billie99** [comment]
Il risultato
​

2017-03-11 1:47 GMT+01:00 Billie Armstrong <billiearmstrong1886@gmail.com>:
