### ISSUE TITLE
the sum (C)

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/C#7]
1 - togli quelle sleep ... (se proprio vuoi aspettare un certo tempo, hai visto nel programma asterischi come farlo in modo corretto)

2 - quando il file non esiste il programma non deve terminare, ma continuare con valori opportuni

**Comment by Billie99** [comment]
Fatto, ho corretto tutto.

**Comment by FabioZTessitore** [comment]
quando il file non esiste il programma deve *continuare* con valori opportuni
